FROM quay.io/pypa/manylinux_2_28_x86_64
ARG ROCM_VER="7.2"

ENV PATH="/root/.cargo/bin:/opt/rocm/bin:/opt/rocm/lib/llvm/bin:${PATH}"
ENV LD_LIBRARY_PATH="/opt/rocm/lib:/opt/rocm/lib64:${LD_LIBRARY_PATH}"
ENV ROCM_PATH=/opt/rocm
ENV HIP_PATH=/opt/rocm
ENV CC=/opt/rh/gcc-toolset-11/root/bin/gcc
ENV CXX=/opt/rh/gcc-toolset-11/root/bin/g++
ENV HIPCC_COMPILE_FLAGS_APPEND="-parallel-jobs=8"
ENV LIBGCC=/opt/rh/gcc-toolset-11/root/usr/lib/gcc/x86_64-redhat-linux/11
ENV LIBRARY_PATH="/opt/rh/gcc-toolset-11/root/usr/lib/gcc/x86_64-redhat-linux/11:/opt/rh/gcc-toolset-11/root/usr/lib64"

WORKDIR /opt
RUN dnf install -y dnf-plugins-core && \
    printf '%s\n' \
        '[rocm]' \
        "name=ROCm ${ROCM_VER} repository" \
        "baseurl=https://repo.radeon.com/rocm/el8/${ROCM_VER}/main" \
        'enabled=1' \
        'priority=50' \
        'gpgcheck=1' \
        'gpgkey=https://repo.radeon.com/rocm/rocm.gpg.key' \
        > /etc/yum.repos.d/rocm.repo && \
    dnf clean all && \
    dnf install -y git curl wget vim glibc-static zlib-devel bzip2-devel ninja-build gcc gcc-c++ libatomic \
        gcc-toolset-11-gcc gcc-toolset-11-gcc-c++ gcc-toolset-11-libatomic-devel gcc-toolset-11-libstdc++-devel \
        rocm-core rocm-llvm rocm-device-libs \
        hipcc hip-devel hsa-rocr-devel \
        hipcub-devel rocprim-devel rocthrust-devel && \
    wget https://github.com/Kitware/CMake/releases/download/v3.31.0/cmake-3.31.0-linux-x86_64.sh && \
    chmod +x cmake-3.31.0-linux-x86_64.sh && \
    ./cmake-3.31.0-linux-x86_64.sh --skip-license --prefix=/usr/local && \
    mkdir /deps && \
    cd /deps && \
    wget https://sourceware.org/pub/bzip2/bzip2-1.0.8.tar.gz && \
    tar xzvf bzip2-1.0.8.tar.gz && \
    cd bzip2-1.0.8 && \
    make install PREFIX=/deps && \
    rm -rf -- /deps/bzip2-1.0.8.tar.gz /deps/bzip2-1.0.8 && \
    cd /deps && \
    wget https://www.zlib.net/zlib-1.3.2.tar.gz && \
    tar xzvf zlib-1.3.2.tar.gz && \
    cd zlib-1.3.2 && \
    ./configure --prefix=/deps --static && \
    make install && \
    rm -rf -- /deps/zlib-1.3.2.tar.gz /deps/zlib-1.3.2 && \
    cd /opt && \
    curl https://sh.rustup.rs -sSf | \
        sh -s -- --default-toolchain stable -y

WORKDIR /work
ADD . .
RUN mkdir -p /work/build && cd /work/build && \
    if [ -e "${LIBGCC}/libgomp.so" ]; then \
        mv -f -- "${LIBGCC}/libgomp.so" "${LIBGCC}/libgomp.so.disabled"; \
    fi && \
    /usr/local/bin/cmake -GNinja -DCMAKE_BUILD_TYPE=Release -DHAVE_TESTS=1 -DENABLE_WERROR=0 -DHAVE_AVX2=1 \
        -DOpenMP_C_FLAGS="-fopenmp -I${LIBGCC} -L${LIBGCC}" -DOpenMP_C_LIB_NAMES=gomp -DOpenMP_CXX_FLAGS="-fopenmp -I${LIBGCC} -L${LIBGCC}" -DOpenMP_CXX_LIB_NAMES=gomp -DOpenMP_gomp_LIBRARY="${LIBGCC}/libgomp.a" \
        -DATOMIC_LIB_OVERRIDE="${LIBGCC}/libatomic.a" \
        -DCMAKE_POLICY_DEFAULT_CMP0074=NEW -DCMAKE_POLICY_DEFAULT_CMP0144=NEW \
        -DZLIB_ROOT=/deps -DBZIP2_ROOT=/deps \
        -DFORCE_STATIC_DEPS=1 -DENABLE_HIP=1 -DCMAKE_HIP_ARCHITECTURES=gfx942 .. && \
    cmake --build . -j"$(nproc --all)" -v

RUN if readelf -Ws /work/build/src/mmseqs | grep -q GLIBC_PRIVATE; then \
        echo "Error: binary contains private glibc symbols"; \
        readelf -Ws /work/build/src/mmseqs; \
        exit 1; \
    fi && \
    LIBC_V=$(readelf -V /work/build/src/mmseqs | awk '$3 ~ /^GLIBC_/ { print $3 }' | sort -V | tail -n1) && \
    if [[ "$LIBC_V" > "GLIBC_2.28" ]]; then \
        echo "Error: glibc too new"; \
        readelf -V /work/build/src/mmseqs; \
        exit 1; \
    fi
